return {
    HANDSHAKE_RES = "HANDSHAKE_RES",
    HEARTBEAT = "HEARTBEAT",
    HEARTBEAT_RES = "HEARTBEAT_RES",
    ERROR = "ERROR",
    DISPATCH_TRAIN = "DISPATCH_TRAIN",
    REGISTER_STATION = "REGISTER_STATION",
    PING = "PING",
    PONG = "PONG",
    HANDSHAKE_CLIENT_STATION = "HANDSHAKE_CLIENT_STATION",
    HANDSHAKE_FACTORY_STATION = "HANDSHAKE_FACTORY_STATION",
    HANDSHAKE_DEPOT_STATION = "HANDSHAKE_DEPOT_STATION"
}